### PR TITLE
checkbox for stock cost system, little rebalance, discounts

### PR DESCRIPTION
**Pull request by yalov**
* checkbox for stock cost system
 * bulk purchase discounts (≥5 kerbals is 15% and 10 kerbals is 30%),   
   BlackMunday discount (day when eclipse occurs),    
   New Year discount;
 * pay x1.25 for choosing gender (male of female),  
   change default gender to random;
 * pay x2 for badass (they pretty unique and should be expensive);
 * low  quality kerbal (Stupidity = 100, Courage = 0) gets x0.5,  
   high quality kerbal (Stupidity = 0, Courage = 100) gets x2.

TODO (can you guys do that?):
 * move  these cost multipliers to config file (line 171);
 * * center vertical align checkbox or;
   * move checkbox into difficulty settings.

50_cr

0_cr_cr
10_cr_cr
15_cr_cr

### CODE REVIEW

**Comment by yalov** [comment]
@TheReadPanda

**Comment by linuxgurugamer** [comment]
Can you post another screenshot showing the latest changes please

**Comment by linuxgurugamer** [comment]
Specifically, where is this checkbox?

**Comment by yalov** [comment]
"Is this Kerbal from Panda Center or Stock Center?"

**Comment by linuxgurugamer** [comment]
Most of the chagnes are very nice, but the switch between stock and panda essentially negates the whole point of this mod, doesn't it?  What's the point of the sliders if you are using stock costs?

**Comment by yalov** [comment]
Someone want use mod's base cost (25000) and apply all modifiers to it, 
but someone want use stock cost as basis, and apply all modifiers to it. 

For example, you can like stock cost system (increasing in time), and want buy nonStupid Kerbal. Then you set "Stock Center" checkbox (better at difficulty setting), and have 
`final_cost = stock_cost * 1.5 (multiplier for nonStupidity)`  etc.
And unchecked "Stock Center" leads
`final_cost = 25000 * 1.5 (multiplier for nonStupidity)`

**Comment by yalov** [comment]
"Stock Center" checkbox is one-time configurable settings, you set your base_cost ideology, and then use it through the game, so it needs to be inside difficulty setting

**Comment by linuxgurugamer** [comment]
So, rather than "stock cost", you just want a configurable base cost
Correct?

**Comment by yalov** [comment]
Configurable base_cost along with configurable multipliers (they are together next to a line 171) is good.

I personally want use stock cost system and mod's functional, allowing me to choose kerbal profession, stats, gender, badass-ness etc, because compared to (increasing) stock any constant value is almost like cheating.

**Comment by linuxgurugamer** [comment]
Setting a configurable base cost and configurable multipliers is not difficult to do.

So, I can do this:   

cost basis:  min stock cost (whatever that is), max 25000
feerless_coef:   min 1, max 3
gender_coef:    min 1, max 2
bulk_discount1: min 0, max 0.2
bulk_discount2: min = bulk_discount1, max of 0.4
black_discount:  min 0, max 0.2  (eclipse day)
new_year_discount: min 0, max 0.75
 
and I'll remove the panda vs stock button

**Comment by yalov** [comment]
how you want to do that?
stock cost depends from ActiveCrewCount, at first stock_cost<25000, then stock_cost >25000

Just move button to difficulty setting.

 const_cost: min 10000, max 100000, default 25000
  stock_cost = GameVariables.Instance.GetRecruitHireCost(HighLogic.CurrentGame.CrewRoster.GetActiveCrewCount());

**Comment by linuxgurugamer** [comment]
Merging this into a dev branch for now

**Pull request merged**
