### PR TITLE
FIFY #6

### PR DESCRIPTION
**Pull request by Sigma88**

### CODE REVIEW

**Comment by Sigma88** [comment]
this fixes #6

**Comment by linuxgurugamer** [comment]
Thank you, but this doesn't do enough.  It fixes the homeplanet name, but deleted the flight log entries which are needed for KSP to give enough XP to get to level 2.

**Comment by Sigma88** [comment]
Training is a stock feature that is used to raise the kerbal's level when generating it

**Comment by linuxgurugamer** [comment]
Really?  I'll try it again,but when I put your code in there, it didn't do the job

**Comment by linuxgurugamer** [comment]
Strange, I don't know why it didn't work earlier, but it's working now.
Thanks, I'll be using your patch

**Comment by Sigma88** [comment]
this is what stock ksp uses to "cheat" up the levels of kerbals

**Comment by linuxgurugamer** [comment]
Understood, thanks.
I've released the update, also fixed the other issue you reported

**Pull request merged**
